apiVersion: batch/v1
kind: Job
metadata:
  name: virat-vr-motion-eval-job
spec:
  template:
    spec:
          containers:
            - name: virat-vr-container
              image:  pytorch/pytorch:1.0.1-cuda10.0-cudnn7-runtime
              imagePullPolicy: Always 
              command: ["/virat-vr/code/pytorch-i3d/setup.sh"]
              args: [ "/virat-vr/code/pytorch-i3d/pytorch_eval.py", "/virat-vr/code/pytorch-i3d/" ]
              resources:
                limits:
                 nvidia.com/gpu: 2
                 memory: "18Gi"
                 cpu: "10"
                 ephemeral-storage: 50Gi
                requests:
                 nvidia.com/gpu: 2
                 memory: "16Gi"
                 cpu: "8" 
                 ephemeral-storage: 50Gi
              volumeMounts:
                - mountPath: /virat-vr
                  name: virat-vr 
                - mountPath: /dev/shm
                  name: dshm
                - mountPath: /mnt/data
                  name: data
          initContainers:
            - name : init-data
              image: gitlab-registry.nautilus.optiputer.net/prp/gsutil
              args:
                - gsutil
                - "-m"
                - rsync
                - "-erP"
                - /mnt/source/
                - /mnt/dest/
              volumeMounts:
                - name: virat-vr-small
                  mountPath: /mnt/source
                - name: data
                  mountPath: /mnt/dest
          restartPolicy: Never
          volumes:
           - name: virat-vr
             persistentVolumeClaim:
               claimName: virat-vr
           - name: virat-vr-small
             persistentVolumeClaim:
               claimName: virat-vr-small
           - name: dshm
             emptyDir:
               medium: Memory
           - name: data
             emptyDir: {}
  backoffLimit: 5
