apiVersion: v1
kind: Pod
metadata:
  name: virat-pytorchpod
spec:
  containers:
  - name: virat-pytorchpod
    image: gitlab-registry.nautilus.optiputer.net/abhay3010/test-prooject
    args: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 2
        memory: "8Gi"
        cpu: "2000m"
      requests:
        nvidia.com/gpu: 2
        memory: "8Gi"
        cpu: "2000m"


    volumeMounts:
    - mountPath: /virat-vr
      name: virat-vr
    - mountPath: /dev/shm
      name: dshm
  restartPolicy: Never
  volumes:
    - name: virat-vr
      persistentVolumeClaim:
        claimName: virat-vr
    - name: dshm
      emptyDir:
        medium: Memory
