apiVersion: v1
kind: Pod
metadata:
  name: virat-pytorchpod
spec:
  containers:
  - name: virat-pytorchpod
    image: gitlab-registry.nautilus.optiputer.net/abhay3010/test-prooject
    args: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: "8Gi"
        cpu: "2000m"
        ephemeral-storage: 10Gi
      requests:
        nvidia.com/gpu: 1
        memory: "8Gi"
        cpu: "2000m"
        ephemeral-storage: 10Gi
    volumeMounts:
    - mountPath: /virat-vr
      name: virat-vr
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /mnt/data
      name: data
  initContainers:
  - name : init-data
    image: gitlab-registry.nautilus.optiputer.net/prp/gsutil
    args:
      - gsutil
      - "-m"
      - rsync
      - "-erP"
      - /mnt/source/
      - /mnt/dest/
    volumeMounts:
      - name: virat-vr-small
        mountPath: /mnt/source
      - name: data
        mountPath: /mnt/dest
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu-type
            operator: In
            values:
            - A100
  volumes:
  - name: virat-vr
    persistentVolumeClaim:
      claimName: virat-vr
  - name: virat-vr-small
    persistentVolumeClaim:
      claimName: virat-vr-small
  - name: dshm
    emptyDir:
      medium: Memory
  - name: data
    emptyDir: {}