apiVersion: batch/v1
kind: Job
metadata:
  name: virat-vr-test-spatial-1-7-v2-1
spec:
  template:
    spec:
      containers:
        - name: virat-vr-container
          image:  gitlab-registry.nautilus.optiputer.net/abhay3010/test-prooject
          imagePullPolicy: Always 
          command: ["/virat-vr/code/pytorch-i3d/setup.sh"]
          args: [ "/virat-vr/code/pytorch-i3d/test.py", "/virat-vr/code/pytorch-i3d/", "ec1_7" ]
          resources:
            limits:
              nvidia.com/gpu: 4
              memory: "10Gi"
              cpu: "3"
              ephemeral-storage: 10Gi
            requests:
              nvidia.com/gpu: 4
              memory: "8Gi"
              cpu: "2500m" 
              ephemeral-storage: 10Gi
          volumeMounts:
            - mountPath: /virat-vr
              name: virat-vr 
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /mnt/data
              name: data
            - mountPath: /virat-vr-r-models
              name: virat-vr-r-models 
      initContainers:
        - name : init-data
          image: gitlab-registry.nautilus.optiputer.net/prp/gsutil
          args:
            - gsutil
            - "-m"
            - rsync
            - "-erP"
            - /mnt/source/
            - /mnt/dest/
          volumeMounts:
            - name: virat-vr-small
              mountPath: /mnt/source
            - name: data
              mountPath: /mnt/dest
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In
                values:
                - "A40"
      volumes:
        - name: virat-vr
          persistentVolumeClaim:
            claimName: virat-vr
        - name: virat-vr-r-models
          persistentVolumeClaim:
            claimName: virat-vr-r-models
        - name: virat-vr-small
          persistentVolumeClaim:
            claimName: virat-vr-small
        - name: dshm
          emptyDir:
            medium: Memory
        - name: data
          emptyDir: {}
  backoffLimit: 5
